/* =========================================================
   Ignite Interior Decors — Interactions (shared across pages)

   Progressive enhancement. All imagery is described by
   gallery-data.js, which is generated by tools/build_gallery.py
   from the category folders in "ignite web site/".

   Sections below:
     1. Category cards + crossfade      (homepage + gallery hub)
     2. Category page: tabs, masonry, lightbox
     3. Shared chrome: reveals, counters, nav, carousels
   ========================================================= */
(function () {
  "use strict";

  const root = document.documentElement;
  root.classList.remove("no-js");
  root.classList.add("js");

  const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const $  = (s, c = document) => c.querySelector(s);
  const $$ = (s, c = document) => Array.from(c.querySelectorAll(s));
  const GALLERY = window.IGNITE_GALLERY || { hero: [], categories: [] };
  const CATS = GALLERY.categories || [];

  /* ---------- rAF-throttled scroll bus ---------- */
  const scrollFns = [];
  let ticking = false;
  const onScroll = (fn) => scrollFns.push(fn);
  const runScroll = () => { scrollFns.forEach((fn) => fn()); ticking = false; };
  window.addEventListener("scroll", () => {
    if (!ticking) { ticking = true; requestAnimationFrame(runScroll); }
  }, { passive: true });

  const esc = (s) => String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

  /* =======================================================
     1. CATEGORY CARDS  (homepage grid + gallery hub)

     Each card stacks up to MAX_STACK photos from its category
     and crossfades between them, so the grid feels alive
     without any hover required.
     ======================================================= */
  const MAX_STACK = 4;

  function catCardHTML(cat) {
    const stack = cat.images.slice(0, MAX_STACK);
    const layers = stack.map((im, i) =>
      `<img class="${i === 0 ? "is-active" : ""}" src="${esc(im.thumb)}"` +
      ` alt="${i === 0 ? esc(cat.name) + " interiors by Ignite Interior Decors" : ""}"` +
      ` loading="${i === 0 ? "eager" : "lazy"}" decoding="async" />`).join("");
    const ticks = stack.map((_, i) =>
      `<i class="${i === 0 ? "is-active" : ""}"></i>`).join("");

    return `
      <a class="cat-card reveal" href="category.html?c=${encodeURIComponent(cat.slug)}"
         aria-label="${esc(cat.name)} — view ${cat.count} photos">
        <span class="cat-rail" aria-hidden="true">
          <span class="cat-rail-name">${esc(cat.name)}</span>
          <span class="cat-rail-count">${cat.count} photos</span>
        </span>
        <span class="cat-media">
          ${layers}
          <span class="cat-ticks" aria-hidden="true">${ticks}</span>
          <span class="cat-open" aria-hidden="true">↗</span>
        </span>
      </a>`;
  }

  function buildCategoryCards() {
    if (!CATS.length) return;
    const targets = [$("#featuredGrid"), $("#categoryHub")].filter(Boolean);
    targets.forEach((grid) => {
      grid.innerHTML = CATS.map(catCardHTML).join("");
    });
    if (targets.length) startCrossfade();
  }

  // Cycle the stacked photos inside every category card.
  function startCrossfade() {
    if (reduceMotion) return;
    $$(".cat-media").forEach((media, order) => {
      const layers = $$("img", media);
      const ticks = $$(".cat-ticks i", media);
      if (layers.length < 2) return;

      let i = 0;
      let timer = null;
      const advance = () => {
        i = (i + 1) % layers.length;
        layers.forEach((el, k) => el.classList.toggle("is-active", k === i));
        ticks.forEach((el, k) => el.classList.toggle("is-active", k === i));
      };
      const play = () => { if (!timer) timer = setInterval(advance, 3400); };
      const stop = () => { clearInterval(timer); timer = null; };

      // Stagger the starts so the whole grid doesn't flip in unison.
      setTimeout(play, order * 650);
      document.addEventListener("visibilitychange", () =>
        document.hidden ? stop() : play());
    });
  }

  /* =======================================================
     2. CATEGORY PAGE — tabs, masonry, lightbox
     ======================================================= */
  function buildCategoryPage() {
    const rootEl = $("#categoryRoot");
    if (!rootEl || rootEl.dataset.page !== "category" || !CATS.length) return;

    const tabsEl = $("#catTabs");
    const grid = $("#masonry");
    let current = -1;

    // ---- tabs ----
    tabsEl.innerHTML = CATS.map((c, i) =>
      `<button type="button" class="cat-tab" role="tab" data-index="${i}">${esc(c.name)}</button>`
    ).join("");
    $$(".cat-tab", tabsEl).forEach((btn) =>
      btn.addEventListener("click", () => show(+btn.dataset.index, true)));

    // ---- masonry row spans, derived from real image dimensions ----
    function layout() {
      const cs = getComputedStyle(grid);
      const row = parseFloat(cs.gridAutoRows) || 8;
      const gap = parseFloat(cs.rowGap || cs.gap) || 18;
      $$(".tile", grid).forEach((tile) => {
        const ar = parseFloat(tile.dataset.ar) || 1.33;   // width / height
        const w = tile.getBoundingClientRect().width;
        if (!w) return;
        const h = w / ar;
        tile.style.gridRowEnd = "span " + Math.ceil((h + gap) / (row + gap));
      });
    }

    // ---- render one category, fading the grid out and back in ----
    function show(i, push) {
      if (i === current || !CATS[i]) return;
      const cat = CATS[i];
      const first = current === -1;
      current = i;

      $$(".cat-tab", tabsEl).forEach((b, k) =>
        b.classList.toggle("is-active", k === i));

      const paint = () => {
        document.title = cat.name + " Interiors — Ignite Interior Decors";
        $("#crumbName").textContent = cat.name;
        $("#catTitle").textContent = cat.name;
        $("#catDesc").textContent = cat.description;

        grid.innerHTML = cat.images.map((im, k) => `
          <figure class="tile" data-ar="${(im.w / im.h).toFixed(4)}" data-index="${k}">
            <img src="${esc(im.thumb)}" alt="${esc(im.alt)}" loading="lazy" decoding="async" />
          </figure>`).join("");

        layout();
        grid.classList.remove("is-swapping");

        // Stagger the tiles in.
        const tiles = $$(".tile", grid);
        tiles.forEach((t, k) => {
          setTimeout(() => t.classList.add("is-in"), reduceMotion ? 0 : Math.min(k, 10) * 55);
          t.addEventListener("click", () => lightbox.open(cat, +t.dataset.index));
        });
      };

      if (first || reduceMotion) {
        paint();
      } else {
        grid.classList.add("is-swapping");
        setTimeout(paint, 300);
      }

      if (push) {
        history.pushState({ c: cat.slug }, "",
          "category.html?c=" + encodeURIComponent(cat.slug));
      }
    }

    // Recompute spans when the grid is resized or fonts/images settle.
    let rz = null;
    window.addEventListener("resize", () => {
      clearTimeout(rz);
      rz = setTimeout(layout, 150);
    });
    window.addEventListener("load", layout);

    // Back/forward between categories.
    window.addEventListener("popstate", () => {
      const slug = new URLSearchParams(location.search).get("c");
      const i = CATS.findIndex((c) => c.slug === slug);
      show(i === -1 ? 0 : i, false);
    });

    const wanted = new URLSearchParams(location.search).get("c");
    const startIdx = CATS.findIndex((c) => c.slug === wanted);
    show(startIdx === -1 ? 0 : startIdx, false);
  }

  /* ---- Lightbox: two buffers slide + crossfade past each other ---- */
  const lightbox = (function () {
    const box = $("#lightbox");
    if (!box) return { open: function () {} };

    const bufs = [$("#lbImgA"), $("#lbImgB")];
    const strip = $("#lbStrip");
    const caption = $("#lbCaption");
    let list = [], idx = 0, front = 0, lastFocus = null;

    function paint(i, dir) {
      const im = list[i];
      if (!im) return;
      idx = i;

      const incoming = bufs[1 - front];
      const outgoing = bufs[front];
      const offset = (dir >= 0 ? 40 : -40) + "px";

      incoming.classList.remove("is-active");
      incoming.style.setProperty("--from", offset);
      incoming.src = im.full;
      incoming.alt = im.alt;
      void incoming.offsetWidth;              // restart the transition
      incoming.classList.add("is-active");

      outgoing.style.setProperty("--from", (dir >= 0 ? -40 : 40) + "px");
      outgoing.classList.remove("is-active");
      front = 1 - front;

      caption.textContent = (i + 1) + " / " + list.length;
      $$("button", strip).forEach((b, k) => b.classList.toggle("is-active", k === i));
      const active = strip.children[i];
      if (active) active.scrollIntoView({ block: "nearest", inline: "center",
        behavior: reduceMotion ? "auto" : "smooth" });
    }

    const next = () => paint((idx + 1) % list.length, 1);
    const prev = () => paint((idx - 1 + list.length) % list.length, -1);

    function open(cat, i) {
      list = cat.images;
      lastFocus = document.activeElement;

      strip.innerHTML = list.map((im, k) =>
        `<button type="button" aria-label="Image ${k + 1}">
           <img src="${esc(im.thumb)}" alt="" loading="lazy" /></button>`).join("");
      $$("button", strip).forEach((b, k) =>
        b.addEventListener("click", () => paint(k, k > idx ? 1 : -1)));

      box.hidden = false;
      document.body.style.overflow = "hidden";
      requestAnimationFrame(() => box.classList.add("is-open"));

      // Show the first frame with no slide, then it's directional.
      bufs.forEach((b) => { b.classList.remove("is-active"); b.style.setProperty("--from", "0px"); });
      front = 1;
      paint(i, 0);
      $("#lbClose").focus();
    }

    function close() {
      box.classList.remove("is-open");
      document.body.style.overflow = "";
      setTimeout(() => { box.hidden = true; }, 400);
      if (lastFocus) lastFocus.focus();
    }

    $("#lbClose").addEventListener("click", close);
    $("#lbNext").addEventListener("click", next);
    $("#lbPrev").addEventListener("click", prev);
    box.addEventListener("click", (e) => {
      if (e.target === box || e.target.id === "lbStage") close();
    });
    document.addEventListener("keydown", (e) => {
      if (box.hidden) return;
      if (e.key === "Escape") close();
      else if (e.key === "ArrowRight") next();
      else if (e.key === "ArrowLeft") prev();
    });

    // Swipe on touch devices.
    let sx = 0;
    $("#lbStage").addEventListener("touchstart", (e) => { sx = e.touches[0].clientX; }, { passive: true });
    $("#lbStage").addEventListener("touchend", (e) => {
      const dx = e.changedTouches[0].clientX - sx;
      if (Math.abs(dx) > 45) (dx < 0 ? next : prev)();
    }, { passive: true });

    return { open: open };
  })();

  buildCategoryCards();
  buildCategoryPage();

  /* =======================================================
     Preloader
     ======================================================= */
  (function preloader() {
    const pre = $(".preloader");
    if (!pre) return;
    const hide = () => {
      root.classList.add("loaded");
      pre.addEventListener("transitionend", () => pre.remove(), { once: true });
      setTimeout(() => pre.remove(), 900);
    };
    window.addEventListener("load", hide);
    setTimeout(hide, 900);
  })();

  /* =======================================================
     Staggered scroll reveal
     ======================================================= */
  (function reveals() {
    let items = $$(".reveal");
    if (!items.length) return;
    if (reduceMotion) { items.forEach((el) => el.classList.add("is-visible")); return; }

    items.forEach((el) => {
      const sibs = Array.from(el.parentElement.children).filter((c) => c.classList.contains("reveal"));
      el.style.transitionDelay = Math.min(sibs.indexOf(el), 6) * 80 + "ms";
    });

    const check = () => {
      const trigger = window.innerHeight * 0.88;
      items = items.filter((el) => {
        if (el.getBoundingClientRect().top < trigger) { el.classList.add("is-visible"); return false; }
        return true;
      });
    };
    onScroll(check);
    check();
  })();

  /* =======================================================
     Count-up stats
     ======================================================= */
  (function counters() {
    let nums = $$(".count");
    if (!nums.length) return;
    const easeOut = (t) => 1 - Math.pow(1 - t, 3);

    const animate = (el) => {
      const target = parseFloat(el.dataset.count) || 0;
      if (el.dataset.plain === "1" || reduceMotion) { el.textContent = target; return; }
      const dur = 1600;
      let start = null;
      const step = (ts) => {
        if (start === null) start = ts;
        const prog = Math.min((ts - start) / dur, 1);
        el.textContent = Math.round(easeOut(prog) * target);
        if (prog < 1) requestAnimationFrame(step);
      };
      requestAnimationFrame(step);
    };

    const check = () => {
      const trigger = window.innerHeight * 0.9;
      nums = nums.filter((el) => {
        const r = el.getBoundingClientRect();
        if (r.top < trigger && r.bottom > 0) { animate(el); return false; }
        return true;
      });
    };
    onScroll(check);
    check();
  })();

  /* =======================================================
     Header state + progress + back-to-top
     ======================================================= */
  (function scrollUI() {
    const header = $(".site-header");
    const progress = $(".scroll-progress");
    const toTop = $(".to-top");
    const update = () => {
      const y = window.scrollY || window.pageYOffset;
      const docH = document.documentElement.scrollHeight - window.innerHeight;
      const ratio = docH > 0 ? y / docH : 0;
      if (header) header.classList.toggle("scrolled", y > 40);
      if (progress) progress.style.setProperty("--progress", ratio.toFixed(4));
      if (toTop) toTop.classList.toggle("show", y > 700);
    };
    onScroll(update);
    update();
    if (toTop) toTop.addEventListener("click", () =>
      window.scrollTo({ top: 0, behavior: reduceMotion ? "auto" : "smooth" }));
  })();

  /* =======================================================
     Scroll-spy active nav (homepage in-page links)
     ======================================================= */
  (function scrollSpy() {
    // Only run on the homepage (has the hero section). On other pages the
    // active nav item is set in the markup, and the header's #top id must
    // not falsely light up "Home".
    if (!$("#hero")) return;
    const links = $$('.main-nav a[href*="#"]').filter((a) => {
      const href = a.getAttribute("href");
      return href.includes("index.html#") && $(href.replace("index.html", ""));
    });
    if (!links.length) return;
    const map = links.map((a) => ({
      link: a, section: $(a.getAttribute("href").replace("index.html", ""))
    })).filter((o) => o.section);
    const update = () => {
      const pos = window.scrollY + 150;
      let cur = null;
      map.forEach((o) => { if (o.section.offsetTop <= pos) cur = o; });
      links.forEach((l) => l.classList.remove("active"));
      if (cur) cur.link.classList.add("active");
    };
    onScroll(update);
    update();
  })();

  /* =======================================================
     Hero carousel (homepage)
     ======================================================= */
  (function heroCarousel() {
    const wrap = $("#heroCarousel");
    if (!wrap) return;
    const slides = $$(".hero-slide", wrap);
    const dots = $$("#heroThumbs button");
    const hero = $(".hero");
    if (slides.length < 2) return;
    let i = 0, timer = null;
    const go = (n) => {
      i = (n + slides.length) % slides.length;
      slides.forEach((s, k) => s.classList.toggle("active", k === i));
      dots.forEach((d, k) => d.classList.toggle("active", k === i));
    };
    const play = () => { if (!reduceMotion) timer = setInterval(() => go(i + 1), 5000); };
    const stop = () => { clearInterval(timer); timer = null; };
    dots.forEach((d, k) => d.addEventListener("click", () => { stop(); go(k); play(); }));
    if (hero) { hero.addEventListener("mouseenter", stop); hero.addEventListener("mouseleave", play); }
    play();
  })();

  /* =======================================================
     Testimonial carousel
     ======================================================= */
  (function testimonials() {
    const track = $(".testimonial-track");
    const prev = $(".carousel-btn.prev");
    const next = $(".carousel-btn.next");
    if (!track) return;
    const step = () => {
      const card = track.querySelector(".testimonial");
      if (!card) return track.clientWidth;
      const gap = parseFloat(getComputedStyle(track).columnGap || getComputedStyle(track).gap) || 24;
      return card.offsetWidth + gap;
    };
    const atEnd = () => track.scrollLeft + track.clientWidth >= track.scrollWidth - 4;
    const behavior = reduceMotion ? "auto" : "smooth";
    const goNext = () => atEnd() ? track.scrollTo({ left: 0, behavior }) : track.scrollBy({ left: step(), behavior });
    const goPrev = () => track.scrollBy({ left: -step(), behavior });
    if (next) next.addEventListener("click", goNext);
    if (prev) prev.addEventListener("click", goPrev);
    if (!reduceMotion) {
      let t = null;
      const play = () => { t = setInterval(goNext, 5000); };
      const stop = () => { clearInterval(t); t = null; };
      play();
      ["mouseenter", "focusin", "touchstart", "pointerdown"].forEach((ev) =>
        track.addEventListener(ev, stop, { passive: true }));
      ["mouseleave", "focusout"].forEach((ev) => track.addEventListener(ev, play));
      document.addEventListener("visibilitychange", () => document.hidden ? stop() : (stop(), play()));
    }
  })();

  /* =======================================================
     Mobile menu
     ======================================================= */
  (function mobileMenu() {
    const toggle = $("#nav-toggle");
    if (!toggle) return;
    const lock = () => { document.body.style.overflow = toggle.checked ? "hidden" : ""; };
    toggle.addEventListener("change", lock);
    $$(".main-nav a").forEach((a) => a.addEventListener("click", () => {
      if (toggle.checked) { toggle.checked = false; lock(); }
    }));
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && toggle.checked) { toggle.checked = false; lock(); }
    });
  })();

  /* =======================================================
     Contact form confirmation
     ======================================================= */
  (function contactForm() {
    const form = $(".contact-form");
    if (!form) return;
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      if (!form.reportValidity()) return;
      const btn = form.querySelector('button[type="submit"]');
      const original = btn.textContent;
      btn.textContent = "Thank you — we'll be in touch ✓";
      btn.classList.add("is-sent");
      btn.disabled = true;
      form.reset();
      setTimeout(() => { btn.textContent = original; btn.classList.remove("is-sent"); btn.disabled = false; }, 3200);
    });
  })();
})();
